README.txt : note you need Python 2
With python 3 you'll get a not-exactly-informative error like:

  File "plot2d.py", line 114
    print "List of runs to analyse:", RUN_LIST
                                   ^
SyntaxError: Missing parentheses in call to 'print'